import json
from typing import List, Dict, Any


def generate_html_template(
    title: str,
    generation_time: str,
    file_path: str,
    coordinates: List[Dict[str, Any]],
    bounds: Dict[str, float]
) -> str:
    """Generate the HTML template for the map visualization.
    
    Args:
        title: Title for the visualization
        generation_time: Timestamp when visualization was generated
        file_path: Name of the input file
        coordinates: List of coordinate data
        bounds: Map bounds dictionary
        
    Returns:
        HTML content as string
    """
    coordinates_json = json.dumps(coordinates)
    bounds_json = json.dumps(bounds)
    
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <link
        rel="stylesheet"
        href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        crossorigin=""
    />
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f8f9fa;
            margin: 0;
            padding: 20px;
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }}
        
        .header {{
            background: #667eea;
            color: white;
            padding: 30px;
            text-align: center;
        }}
        
        .header h1 {{
            margin: 0 0 10px 0;
            font-size: 2.2em;
        }}
        
        .content {{
            padding: 30px;
        }}
        
        .section {{
            margin-bottom: 40px;
        }}
        
        .section h2 {{
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        
        .config-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
        }}
        
        .config-item {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            border-left: 4px solid #667eea;
        }}
        
        .config-item strong {{
            color: #667eea;
        }}
        
        #map {{
            height: 600px;
            width: 100%;
            border-radius: 8px;
            margin-top: 20px;
        }}
        
        .legend {{
            background: white;
            padding: 10px;
            border-radius: 5px;
            box-shadow: 0 1px 5px rgba(0,0,0,0.4);
        }}
        
        .legend h4 {{
            margin: 0 0 5px;
            color: #333;
        }}
        
        .footer {{
            text-align: center;
            padding: 20px;
            color: #666;
            border-top: 1px solid #ddd;
            background: #f8f9fa;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{title}</h1>
            <div>Generated on {generation_time}</div>
        </div>

        <div class="content">
            <div class="section">
                <h2>Flight Path Visualization</h2>
                <div class="config-grid">
                    <div class="config-item">
                        <strong>Input Data:</strong><br>
                        {file_path}
                    </div>
                    <div class="config-item">
                        <strong>Total Points:</strong><br>
                        {len(coordinates)}
                    </div>
                    <div class="config-item">
                        <strong>Bounds (WGS-84):</strong><br>
                        {bounds['south']:.4f}, {bounds['west']:.4f}<br>
                        to {bounds['north']:.4f}, {bounds['east']:.4f}
                    </div>
                </div>
                
                <div id="map"></div>
            </div>
        </div>
        
        <div class="footer">
            <p>Visualization generated by FVC Tools</p>
            <p>For questions or support, contact: boris@flyver.city</p>
        </div>
    </div>

    <script
        src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossorigin=""
    ></script>
    <script src="map.js"></script>
    <script>
        // Initialize the map with data
        initializeMap(
            {bounds_json},
            {coordinates_json}
        );
    </script>
</body>
</html>'''


def generate_js_template() -> str:
    """Generate the JavaScript template for the map functionality.
    
    Returns:
        JavaScript content as string
    """
    return '''// FVC Tools Map Visualization JavaScript
var map;
var geo_bounds;
var coordinates;

function initializeMap(boundsData, coordinatesData) {
    geo_bounds = boundsData;
    coordinates = coordinatesData;
    
    var bounds = [
        [geo_bounds.south, geo_bounds.west],
        [geo_bounds.north, geo_bounds.east]
    ];

    map = L.map('map').fitBounds(bounds);

    let attribution = '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>';

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: attribution
    }).addTo(map);

    // Create flight path line
    var pathCoords = coordinates.map(function(coord) {
        return [coord.lat, coord.lon];
    });
    
    var flightPath = L.polyline(pathCoords, {
        color: '#667eea',
        weight: 3,
        opacity: 0.8
    }).addTo(map);

    // Add markers for start and end points
    if (coordinates.length > 0) {
        var startPoint = coordinates[0];
        var endPoint = coordinates[coordinates.length - 1];
        
        L.marker([startPoint.lat, startPoint.lon], {
            icon: L.divIcon({
                className: 'start-marker',
                html: '<div style="background-color: #28a745; width: 12px; height: 12px; border-radius: 50%; border: 2px solid white;"></div>',
                iconSize: [12, 12]
            })
        }).addTo(map).bindPopup('Start Point');
        
        L.marker([endPoint.lat, endPoint.lon], {
            icon: L.divIcon({
                className: 'end-marker',
                html: '<div style="background-color: #dc3545; width: 12px; height: 12px; border-radius: 50%; border: 2px solid white;"></div>',
                iconSize: [12, 12]
            })
        }).addTo(map).bindPopup('End Point');
    }

    // Add legend
    var legend = L.control({position: 'bottomright'});
    legend.onAdd = function (map) {
        var div = L.DomUtil.create('div', 'info legend');
        div.innerHTML = '<h4>Flight Path</h4>' +
                       '<div style="display: flex; align-items: center; margin: 5px 0;">' +
                       '<div style="background-color: #28a745; width: 12px; height: 12px; border-radius: 50%; margin-right: 8px;"></div> Start Point</div>' +
                       '<div style="display: flex; align-items: center; margin: 5px 0;">' +
                       '<div style="background-color: #dc3545; width: 12px; height: 12px; border-radius: 50%; margin-right: 8px;"></div> End Point</div>' +
                       '<div style="display: flex; align-items: center; margin: 5px 0;">' +
                       '<div style="background-color: #667eea; width: 20px; height: 3px; margin-right: 8px;"></div> Flight Path</div>' +
                       '<small>Total points: ' + coordinates.length + '</small>';
        return div;
    };
    legend.addTo(map);
}'''
